# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

urls = %w[
  https://youtube.com
  https://en.wikipedia.org
  https://facebook.com
  https://amazon.com
  https://imdb.com
  https://reddit.com
  https://pinterest.com
  https://ebay.com
  https://instagram.com
  https://google.com
  https://nytimes.com
  https://apple.com
  https://walmart.com
  https://apple.com
  https://linkedin.com
  https://indeed.com
  https://espn.com
  https://etsy.com
  https://asdfhafsdlkj.com
  https://netflix.com
  https://quora.com
  https://microsoft.com
  https://target.com
  https://merriam-webster.com
  https://forbes.com
  https://mapquest.com
  https://nih.gov
  https://gamepedia.com
  https://yahoo.com
  https://foxnews.com
  https://allrecipes.com
  https://quizlet.com
  https://weather.com
  https://bestbuy.com
  https://urbandictionary.com
  https://mayoclinic.org
  https://aol.com
  https://zillow.com
  https://usatoday.com
  https://msn.com
  https://rottentomatoes.com
  https://lowes.com
  https://businessinsider.com
  https://usnews.com
  https://washingtonpost.com
  https://finance.yahoo.com
  https://yellowpages.com
  https://retailmenot.com
  https://accuweather.com
  https://live.com
  https://wayfair.com
  https://login.yahoo.com
  https://steamcommunity.com
  https://cnet.com
  https://ign.com
  https://steampowered.com
  https://macys.com
  https://wikihow.com
  https://wiktionary.org
  https://cbssports.com
  https://cnbc.com
  https://bankofamerica.com
  https://expedia.com
  https://wellsfargo.com
  https://groupon.com
  https://twitch.tv
  https://khanacademy.org
  https://theguardian.com
  https://paypal.com
  https://spotify.com
  https://att.com
  https://nfl.com
  https://goodreads.com
  https://office.com
  https://ufl.edu
  https://mlb.com
  https://foodnetwork.com
  https://bbc.com
  https://apartments.com
  https://npr.org
  https://wowhead.com
  https://support.google.com
  https://bit.ly
  https://techcrunch.com
  https://harvard.edu
  https://wsj.com
  https://archive.org
  https://rakuten.co.jp
  https://groups.google.com
  https://tools.google.com
  https://aliexpress.com
  https://surveymonkey.com
  https://globo.com
  https://disqus.com
  https://bing.com
  https://www.bluecoding.com
  https://hp.com
  https://oracle.com
  https://playstation.com
  https://ted.com
  https://www.gov.uk
  https://nypost.com
  https://ooinfadsonisfnois.com
  https://fsafasdfsdafdsa.com
  https://rwqewqreqwreeqwr.com
  https://nwenkleknlerknre.com
  https://nqrekjlkwjqrenqwerkj.com
  https://qrnqwrenkkwqer.com
  https://nqkrnkwlqrenwkre.com
  https://qoreoqrewjoire.com
  https://oipasfosfdo.com
  https://ojiafsjisafdj.com
  http://storage.googleapis.com/
  http://fedoraproject.org/
  http://nbcnews.com/
  http://scientificamerican.com/
  http://cbslocal.com/
  http://uspto.gov/
  http://steamcommunity.com/
  http://symantec.com/
  http://disney.go.com/
  http://dribbble.com/
  http://ehow.com/
  http://fifa.com/
  http://thoughtco.com/
  http://teamviewer.com/
  http://greenpeace.org/
  http://usa.gov/
  http://thefreedictionary.com/
  http://businesswire.com/
  http://www.youtube.com
  http://www.facebook.com
  http://www.baidu.com
  http://www.yahoo.com
  http://www.amazon.com
  http://www.wikipedia.org
  http://www.qq.com
  http://www.google.co.in
  http://www.twitter.com
  http://www.live.com
  http://www.taobao.com
  http://www.bing.com
  http://www.instagram.com
  http://www.weibo.com
  http://www.sina.com.cn
  http://www.linkedin.com
  http://www.yahoo.co.jp
  http://www.msn.com
  http://www.vk.com
  http://www.google.de
  http://www.yandex.ru
  http://www.hao123.com
  http://www.google.co.uk
  http://www.reddit.com
  http://www.ebay.com
  http://www.google.fr
  http://www.t.co
  http://www.tmall.com
  http://www.google.com.br
  http://www.360.cn
  http://www.sohu.com
  http://www.amazon.co.jp
  http://www.pinterest.com
  http://www.netflix.com
  http://www.google.it
  http://www.google.ru
  http://www.microsoft.com
  http://www.google.es
  http://www.wordpress.com
  http://www.gmw.cn
  http://www.tumblr.com
  http://www.paypal.com
  http://www.blogspot.com
  http://www.imgur.com
  http://www.stackoverflow.com
  http://www.aliexpress.com
  http://www.naver.com
  http://www.ok.ru
  http://www.apple.com
  http://www.github.com
  http://www.chinadaily.com.cn
  http://www.imdb.com
  http://www.google.co.kr
  http://www.fc2.com
  http://www.jd.com
  http://www.blogger.com
  http://www.163.com
  http://www.google.ca
  http://www.whatsapp.com
  http://www.amazon.in
  http://www.office.com
  http://www.tianya.cn
  http://www.google.co.id
  http://www.youku.com
  http://www.rakuten.co.jp
  http://www.craigslist.org
  http://www.amazon.de
  http://www.nicovideo.jp
  http://www.google.pl
  http://www.soso.com
  http://www.bilibili.com
  http://www.dropbox.com
  http://www.xinhuanet.com
  http://www.outbrain.com
  http://www.pixnet.net
  http://www.alibaba.com
  http://www.alipay.com
  http://www.microsoftonline.com
  http://www.booking.com
  http://www.googleusercontent.com
  http://www.google.com.au
  http://www.popads.net
  http://www.cntv.cn
  http://www.zhihu.com
  http://www.amazon.co.uk
  http://www.diply.com
  http://www.coccoc.com
  http://www.cnn.com
  http://www.bbc.co.uk
  http://www.twitch.tv
  http://www.wikia.com
  http://www.google.co.th
  http://www.go.com
  http://www.google.com.ph
  http://www.doubleclick.net
  http://www.onet.pl
  http://www.googleadservices.com
  http://www.accuweather.com
  http://www.googleweblight.com
  http://www.answers.yahoo.com
]

while Url.count < 200 do
  url = urls.sample
  puts "URL: #{url}"
  new_url = Url.find_or_initialize_by(full_url: url, hit_counter: rand(3000))
  new_url.save
end